name: CI
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
      destination:
        description: 'Where do you want to install?'
      compress:
        type: boolean
        required: false
        description: Do you want to compress and upload?

jobs:
  GitBIT:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
    - name: install_dependencies
      run: |
          sudo apt-get update -y -qq
          sudo apt-get install transmission-cli 
    - name: Grab
      run: |
       tmpfile=$(mktemp)
       chmod a+x $tmpfile
       echo "killall transmission-cli" > $tmpfile
       transmission-cli -f $tmpfile ${{ github.event.inputs.url }} -w ${{ github.event.inputs.destination }}
      continue-on-error: true 
    - name: Compress
      if: inputs.compress
      run: tar -czvf download.tar.gz .
    - name: Upload compressed artifact
      if: inputs.compress
      uses: actions/upload-artifact@v4
      with:
        name: Torrent
        path: download.tar.gz
    - name: Upload uncompressed artifact 
      if: github.event.inputs.compress == false
      uses: actions/upload-artifact@v4
      with:
        name: Torrent
        path: ${{github.workspace}}

